fix(ci): Multi-platform build is not supported for the docker driver. (#5)
* Fix release version

* fix(ci): Adds support ot QEMU

Fix errors:

```
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
Error: buildx failed with: Learn more at https://docs.docker.com/go/build-multi-platform/
```

* feat(ci): Add support to dockerhub